# Generated by Django 3.2.5 on 2021-07-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_auto_20210724_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Imagez',
        ),
    ]
