# Generated by Django 3.2.5 on 2021-07-26 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_rename_image_imagez'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagez',
            name='output',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
