# Generated by Django 3.2.5 on 2021-07-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_imagez_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagez',
            name='output',
            field=models.TextField(default='hello working fine'),
        ),
    ]
